### ISSUE TITLE
alarm control panel with code

### ISSUE THREAD

**Issue by MrBramme** [home-assistant/homebridge-homeassistant#191]
Cannot set the alarm if a code is required. it works just fine without code.
Need to find a way to set this in the config.

**Comment by robbiet480** [comment]
HomeKit itself doesn't support alarm control panels with codes as per the [HAP-NodeJS spec](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L3056-L3076). @schmittx wanna weigh in?

**Comment by MrBramme** [comment]
I was thinking something along the lines of adding the code to the homebridge config, pointing to a specific alarm panel (to allow multiple).
If I have some time this weekend I'll try to investigate that path as well

**Comment by schmittx** [comment]
@MrBramme good suggestion, my alarm doesn't use a code via HomeAssistant so I never considered that. I agree with your idea, although it'd be easiest to attach the code to the alarm entity itself via customize (i.e. "homebridge_alarm_code: 1234"). I'll look into something this weekend, any chance you can share some sample code for the service calls (i.e. arm, disarm, etc.) to HomeAssistant when using a code so that I can understand the format?

**Comment by MrBramme** [comment]
@schmittx I don't need the code to be honest, I just activated it as another level of security. That being said, your suggestion does appear to be the better option.
As for sample code for the service calls, I'll have to take a look at it in more detail but it's sufficient to add the json property {"code" : "1234"} to the call to fix it. 

for example this json object to the arm/disarm/... call : 
`{"entity_id" :"alarm_control_panel.panel1",
"code":"1234" }`

**Comment by schmittx** [comment]
@MrBramme Extra security is always good, I think this should be doable. Thanks for the format also, it really helps!
