### ISSUE TITLE
SONOS media_player displays incorrect state

### ISSUE THREAD

**Issue by jamieshaw** [home-assistant/homebridge-homeassistant#193]
Since upgrading to 2.2.1, the 'switch' that is used to control the SONOS in my home commonly shows the state of the device as 'on'.

The HomeKit object can be used to correctly start/stop the SONOS, and updates it's state in HomeKit accordingly, but if the device is changed _outside_ of HomeKit, then the state will remain as the last known state inside HomeKit.

It also appears that on startup, the SONOS defaults to "on" despite being Off (Paused) both physically and in Home Assistant.

I'm assuming this correlates to the new `homebridge_media_player_switch` attribute, however, after trying all three options. This seems to make little difference.

**Running:**
- Home Assistant 0.49.0
- Homebridge 0.4.22
- Homebridge-Homeassistant 2.2.1

**Comment by riverscn** [comment]
Also with my Sony Bravia TV and X77 Speaker and Nvidia Shield.

**Comment by robbiet480** [comment]
@azogue ?

**Comment by azogue** [comment]
Don't know @robbiet480, could be because the logic negation?
We went from `const powerState = data.state === this.onState;` to `const powerState = data.state !== this.offState;` in #183. 
If I understand correctly, the Sonos is working as a `play_pause` device, isn't it? Well, when paused, what is its `state` exactly? (if it is not exactly 'paused', that would be the error)

Could be because at start, the state is 'unknown' or other than 'paused'?

I changed that because for 'on_off' media players, the 'on' state is a multiple one (anything that isn't 'off'), but it looks like the state logic depends of `homebridge_media_player_switch`, what do you think?

**Comment by azogue** [comment]
I can revert the state logic for players that aren't working as 'on_off' devices, but I can't test it, do you want me to do the PR, @robbiet480?

**Comment by jamieshaw** [comment]
Had 5 minutes to figure out how to pull a specific branch down through NPM.  Tested @azogue's branch used for #200 and can confirm it works as functioned now. Both with local tracks and radio streams.

Just waiting for the PR to be accepted.

**Comment by robbiet480** [comment]
PR merged!
