### ISSUE TITLE
Default color temperature values

### ISSUE THREAD

**Issue by NovapaX** [home-assistant/homebridge-homeassistant#246]
When no homebridge specific min/max values are configured it seems to me that it would be a logical thing to fallback to using 'min_mireds' and 'max_mireds' from entity attributes if defined.

So first try 'homebridge_min_mireds' and 'homebridge_max_mireds'
then try 'min_mireds' and 'max_mireds'
and then fall back to default of 50 and 400

I have no time currently to write the code (it's not that much of course, a little code change here: https://github.com/home-assistant/homebridge-homeassistant/blob/bd07d36cee396e456987cb738c8bee3b4a2370d9/accessories/light.js#L118)
And I certainly have no way (yet) to test it. Sorry for that. I want to contribute, but still setting things up.

**Comment by schmittx** [comment]
I used that method initially, but it didn't have the best results because Home Assistant doesn't report `max_mireds` and `min_mireds` when the lightbulb is turned off (at least for my LIFX bulbs). As a result, the color temperature range would fluctuate and sometimes become unresponsive.

If you can test and get different results than me, then I'm all for it. But from my initial checking, the current method seemed to be the most reliable and robust (even though it's admittedly a pain to setup initially).

**Comment by donnib** [comment]
I see the same thing, the information is not available when lights are off. Maybe this is something that can be discussed with @balloob, do you have a comment for this ? Is there a good way for @schmittx to get this info ?
