### ISSUE TITLE
Rollershutter State terminology

### ISSUE THREAD

**Issue by KmanOz** [home-assistant/homebridge-homeassistant#25]
Hi

First off great work incorporating Rollershutter. I use Rollershutter via mqtt to control my Garage Rollerdoor. I do so because it on screen it's UI is more intuitive than the Garage Door component which is just a switch. I discovered when I first started playing with it that OPEN & CLOSED referred to to the state of the actual Rollershutter rather than the state of the space it left. An open door means an open space that you can walk through but with Rollershutter, OPEN Rollershutter = CLOSED space which you cannot drive through. I didn't understand the logic at first but it does make sense to speak of it based on the state of the actual Rollershutter I guess.

I just changed the logic in my automation and lived with it but now the state is reversed in Apple's Home app once again with the new Rollsershutter support. On the HA UI if the UP arrow is active it means the Rollershutter is OPEN or DOWN and vice versa. Considering the service to actuate the Rollershutter is rollershutter.move_up & down respectively, can the state of the door be reported back to Homekit as UP or DOWN rather than OPEN or CLOSED. This will make it universal and can be used and understood by anyone irrespective of how they use the component.

Thanks

**Comment by n8henrie** [comment]
I was about to make a similar issue but will just jump in here if that's okay. For the purpose of this discussion (and given that the issue is regarding inversion of the meaning of open and closed), I'll define a "closed / secured" rollershutter as "one you can't walk through" (which hass refers to as "fully open / unrolled").

@maddox -- would you consider rolling back https://github.com/home-assistant/homebridge-homeassistant/commit/9b5b01221cb363a2f81fad813be372ae5615cf7e and replacing it with my version at https://github.com/home-assistant/homebridge-homeassistant/pull/21 ?

I think it better addresses the rollershutter component in a few ways --

1. One, in relation to this issue, I've found this behavior confusing and as a result I'm making (slow) progress towards rectifying it in hass (see https://github.com/home-assistant/home-assistant/issues/1949 , https://github.com/home-assistant/home-assistant-polymer/pull/54). Because I'm familiar with the issue and also find it confusing, I [commented my code fairly heavily](https://github.com/n8henrie/homebridge-homeassistant/blob/038d81c0e9d68ee110924501639a914f553c3c46/accessories/rollershutter.js#L32) to try to advertise this behavior to other users, including links to the relevant hass discussions and HAP-NodeJS source files.
2. The version that got merged uses [a position of 50](https://github.com/home-assistant/homebridge-homeassistant/blob/9b5b01221cb363a2f81fad813be372ae5615cf7e/accessories/rollershutter.js#L70) to determine open / closed status. While this makes sense at first blush, I consider it a serious home security problem; HomeKit will report a garage door to be fully closed / secured even if it is nearly halfway open. My PR uses code that [only reports a rollershutter as closed / secured if it is completed closed / secured](https://github.com/n8henrie/homebridge-homeassistant/blob/038d81c0e9d68ee110924501639a914f553c3c46/accessories/rollershutter.js#L38). While this could be problematic in cases where a rollershutter that is 99% closed / secured is reported as open (because it's not *100%*), I think that's a far better problem to have than thinking your rollershutter is secured when it's actually 49% open / unsecured.

I don't know much javascript, so if there are significant code quality advantages to the PR you accepted, I could alternatively make separate issues and PRs to merge in my explanatory code comments, as well as a second one to perhaps make a configurable threshold for considering the rollershutter closed... but if there were no major issues with my code, just overwriting the existing rollershutter accessory with mine would seem easier.

**Comment by maddox** [comment]
>> I don't know much javascript, so if there are significant code quality advantages to the PR you accepted, I could alternatively make separate issues and PRs to merge in my explanatory code comments

I honestly just picked the first one to be fair, thinking that they were basically the same.

Having no roller shutters or garage door, not only do I have no way to try this, I don't know the nuances of the UX involved in using these. But your arguments sound good for sure.

@robbiet480 want to add any input here?

**Comment by robbiet480** [comment]
I'm in the same boat as @maddox on this, no roller shutters or garage door so no way to test and I don't fully understand the UX.

So, kicking the can down the road a bit....

@Marioheld want to add any input here?

**Comment by Marioheld** [comment]
My code was just a fast and dirty implementation for Rollershutters so go ahead and use @n8henrie patch. When I tested the patch I was running a iOS beta version so maybe there were the directions reversed. When I try it on the current iOS version it is also reversed for me but I didn't found the time to change it. Also to claim that a Garagedoor is not really closed when it is reported because of my 50/50 test is true. Didn't had this in mind. It was also a hack, as commented in the code, because HA sadly does not support to set a position between 0 and 100 only open and close.

**Comment by robbiet480** [comment]
Okay. I'll take care of reverting and merging now.

**Comment by robbiet480** [comment]
Done! Will be releasing 1.5.0 shortly.
