### ISSUE TITLE
duplicate events being received

### ISSUE THREAD

**Issue by ErnstEeldert** [home-assistant/homebridge-homeassistant#280]
My setup is like this:

deCONZ -> Home Assistant -> homebridge-homeassistant -> homekit

Sometimes, the system gets into a state where lots of duplicate events seem to be fired/processed by homebridge-homeassistant. I can see that deCONZ is firing a single event, and also that Home Assistant is firing a single event based on this. However, on the homebridge-homeassistant side of things 8 events are shown in the logs:

[kantoor_deconz_on.log](https://github.com/home-assistant/homebridge-homeassistant/files/1698419/kantoor_deconz_on.log)
[kantoor_on.log](https://github.com/home-assistant/homebridge-homeassistant/files/1698420/kantoor_on.log)

I am not sure if it's just a logging issue, or that the actual events are duplicated somewhere. Perhaps because of duplicate connections?

Any suggestions on how to troubleshoot this? Thanks!

**Comment by kasparsv** [comment]
I'm not sure if this is related, but I'm also seeing duplicate events from Homebridge on homeassistant (Hass.io homebridge plugin).

I have a Sonoff LED strip (based on ESP8266) w/ Tasmota latest firmware.

When I turn on power via iPhone Homekit, duplicate MQTT commands are sent:
`# mosquitto_sub -h 10.0.1.16 -v -t test/#
test/tele/sonoffLED/LWT Online
test/cmnd/sonoffLED/DIMMER 99
test/stat/sonoffLED/RESULT {"POWER":"ON","Dimmer":99,"Color":"6,244","CT":489}
test/cmnd/sonoffLED/DIMMER 99
test/stat/sonoffLED/RESULT {"POWER":"ON","Dimmer":99,"Color":"6,244","CT":489}`

When I turn on power via Home assistant interface, only single command is sent:
`test/cmnd/sonoffLED/DIMMER 99
test/stat/sonoffLED/RESULT {"POWER":"ON","Dimmer":99,"Color":"6,244","CT":489}`

Note that in my configuration I'm turning on Power via DIMMER command, but the same happens when I change to POWER command.

The duplicate commands result in a lot unnecessary MQTT traffic e.g. when using dimmer from Homekit slowing down performance as the light itself and HA tries to process every message and resulting status update.

See below what happens when I use Siri to set Dimmer to specific percentage:
`# mosquitto_sub -h 10.0.1.16 -v -t test/#
test/tele/sonoffLED/LWT Online
test/cmnd/sonoffLED/DIMMER 87
test/stat/sonoffLED/RESULT {"POWER":"ON","Dimmer":87,"Color":"6,214","CT":489}
test/cmnd/sonoffLED/DIMMER 19
test/stat/sonoffLED/RESULT {"POWER":"ON","Dimmer":19,"Color":"1,46","CT":489}
`
The first command is unnecessary duplicate.
