### ISSUE TITLE
Climate showing as fan, 2 climates

### ISSUE THREAD

**Issue by remco770** [home-assistant/homebridge-homeassistant#294]
Since release 3.1 my climate is showing double. It's visible as a fan and normal.
Normal is not working since it still says updating, (Git issue #285). But after this update there is a new accessoires witch indicates a fan. There is no fan within my climate, since it's used to heat my home

![4775681c-ac7a-442e-b713-68855d90b355](https://user-images.githubusercontent.com/3218408/36219070-8d42c964-11b6-11e8-8ba2-8817bdc77386.jpeg)

**Comment by Martinvdm** [comment]
Same issue here. Climate is now shown twice. Once as Climate and once again as Fan. 
The fan version is showing status Off and the Climate version is showing Updating... but never finishes.

**Comment by schmittx** [comment]
This enhancement was added with #244, the fan service allows you to control the blower within the HVAC system manually (i.e. turn on the blower without A/C or heat).

However, I haven't tested personally so there may still be some bugs present. The climate support in this plugin is still maturing due to the wide array of climate components within Home Assisstant.

**Comment by Martinvdm** [comment]
I understand the feature but outside the US the most thermostates does not have a blower at all. Isn't better to make an config option for this e.g. homebridge_climate_type or somehow honor the thermostat options from homeassistant.

**Comment by schmittx** [comment]
@Martinvdm I agree, ultimately we should use the `supported_features` from Home Assistant to determine what services/characteristics to create (similar to how media players work for this plugin, see also #281 ). This is the plan for the next release.

**Comment by Martinvdm** [comment]
Great! perhaps it solves another issues [285](https://github.com/home-assistant/homebridge-homeassistant/issues/285) and [273 ](https://github.com/home-assistant/homebridge-homeassistant/issues/273) at the same time, because it is only updating the needed values from home assistant in the first place.

**Comment by 5chacha5** [comment]
hey there,

I'm new in home assistant so I'm not a expert like all of you...

I have a Broadlink rm mini 3 to control my aircondionner (hot and cold) and I wish a thermostat and a fan to control this. How I can do this ?

Thanks a lot for your help !

**Comment by maddox** [comment]
Hi @5chacha5! 

GitHub issues are for discussing development of features. This repo specifically isn't even for Home Assistant itself, but software that bridges your devices from Home Assistant to HomeKit.

Check out the Home Assistant community at https://community.home-assistant.io. That's the place to look for help or help others.

Thanks!

**Comment by remco770** [comment]
Since there seems to be a fix in #303 
@schmittx could you please release a new version?

**Comment by tobsch** [comment]
+1
