### ISSUE TITLE
Aeotec Sensor 6

### ISSUE THREAD

**Issue by jcastro** [home-assistant/homebridge-homeassistant#3]
Hello!

Would I be able to access this sensor information from HomeKit using this plugin? It seems I won't, but wanted to check wether it would be possible or if it was something you could add support to if you have time for that

Thanks for this plugin!

**Comment by maddox** [comment]
No, sensors are not currently bridged over. The components that are bridged are: lights, media_players, switches, and scenes.

I didn't add sensors because my thought was that they’d only be useful for doing automations with HomeKit itself. And not only did I think no one would care about that, I actively disagree with it and don’t think you should. Everything should be in Home Assistant.

This plugin is designed to just allow Siri to be a front end for Home Assistant. That being said, it does make some sense to expose sensors so you can ask siri what the temperature is in a room. 

I’ll look at adding it soon.

**Comment by jcastro** [comment]
Well I think it's always better to have as much support as possible. I agree with you, it's better to do the automation in one place if possible. But for example it could happen that some HomeKit compatible device doesn't have support for HA, so you can't do automation with the sensor there. If the sensor is HA compatible then I could do it on HomeKit. Just thinking out loud!

**Comment by abouzek** [comment]
I am going to work on this myself and create a pull when I'm done. The reason is I have Lutron Caseta dimmers with a Smart Bridge (NOT Pro version) which has HomeKit compatibility, but is not remotely accessable via an API and is proprietary so Home Assistant cannot integrate it.

I plan to have an always-on iOS device to set up integrations with the Lutron Casetas specifically.

**Comment by robertvorthman** [comment]
I also have some HomeKit devices which do not support HA.  It would be great if I could use Home Assistant's sophisticated presence detection to trigger HomeKit scenes.  HomeKit's geofencing isn't practical if you live alone, I don't want to turn stuff off on my wife just because I leave the house.

**Comment by jmesaunders** [comment]
I agree with @maddox, that's how I've been planning to use HomeKit and Home Assistant. I wanted the front end, Home app, Control Centre and Siri support, whilst maintaining everything through HA.

However, the more devices the merrier!

**Comment by maddox** [comment]
This is still how I feel. I'm going to close this now.

Anyone can feel free to open another issue if better arguments arise.
