### ISSUE TITLE
No binary sensors show up

### ISSUE THREAD

**Issue by jsg4** [home-assistant/homebridge-homeassistant#61]
In latest version, sensors are now showing (awesome!), but binary sensors are not. Here's my config. 

```json
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 8128,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "HomeAssistant",
      "name": "HomeAssistant",
      "host": "http://192.168.1.242:8123",
      "password": "password",
      "supported_types": [
        "binary_sensor",
        "fan",
        "light",
        "lock",
        "scene",
        "sensor",
        "switch"
      ]
    },
    {
      "platform": "Nest",
      "token": "token",
      "clientId": "client",
      "clientSecret": "secret",
      "code": "code"
    },
    {
      "platform": "LiftMaster2",
      "username": "username",
      "password": "password"
    }
  ]
}
```

**Comment by robbiet480** [comment]
I'm seeing `binary_sensor`s with a `sensor_class` of `motion` and `opening`. Please note that only a few `sensor_class`es are currently supported due to limitations in HomeKit. If you use the same `/api/states` trick I showed you earlier you can inspect what `sensor_class` your `binary_sensor`s have. The currently supported ones are `moisture`, `motion`, `occupancy`, `opening`, `smoke`.

**Comment by robbiet480** [comment]
This was due to missing `sensor_class`. I added an error in https://github.com/home-assistant/homebridge-homeassistant/commit/2a8d9b3972d53893955e29143cda1a700eca3da6 to warn people if they have enabled `binary_sensor` without having a `sensor_class` set.
