### ISSUE TITLE
NPM not updated?

### ISSUE THREAD

**Issue by olines** [home-assistant/homebridge-homeassistant#64]
Hi, I am trying to get binary_sensor to show up but it appears that NPM (https://www.npmjs.com/package/homebridge-homeassistant) is not updated?

How do I get the latest (from here) to show up in homebridge?  I'm running it in a docker container on a Synology NAS.

Thank you!

**Comment by robbiet480** [comment]
This is intentional currently. We are doing this because everything is a bit unstable as of late with many core changes.

Instead of doing `npm install -g homebridge-homeassistant` in the meantime you need to do `npm install -g home-assistant/homebridge-homeassistant` to install it from Github directly.

We are currently targeting next weekend to release version 2.0.0 of homebridge-homeassistant along with Home Assistant 0.32.

**Comment by olines** [comment]
Thanks, that worked.  package.json updated as follows:
 ```
{  "scripts": {
    "install": "npm install -g homebridge-wink homebridge-liftmaster2 homebridge-nest home-assistant/homebridge-homeassistant --unsafe-perm"
  }
}
```

**Comment by robbiet480** [comment]
2.0.0 has just been published to npm. You can now use the standard install command again.
