### ISSUE TITLE
Inform homebridge about changed state

### ISSUE THREAD

**Issue by ulope** [home-assistant/homebridge-homeassistant#8]
Unless I missed something in the configuration it seems that state changes (i.e. switching a light) are not reported to homebridge.

It would be nice if the two "views" would be consistent.

**Comment by KmanOz** [comment]
Upgraded to 1.6.0 today. Uni-directional status worked for 20 minutes then went back to one-way. Terminated service and started it again without rebooting server. Back up and running. Only happened once but will report if it happens again

**Comment by robbiet480** [comment]
@shmuelzon any ideas about @KmanOz's issue?

**Comment by shmuelzon** [comment]
Didn't even know a new release was out :)

Anyways, hard to tell what might be wrong with the current information. I'm away from my PC (and relevant repositories) but a few things worth exploring:

* HAP-NodeJS's logs (run homebridge prefixed with `DEBUG=*`) and check the logs. Are events not reaching homebridge, or not reaching the mobile device?
* Next time this happens, please try to disconnect you phone from the network and connect it again, forcing it to reconnect to the server (and register for changes again)
* What happens if the SSE HTTP connection is broken? Does it try to reconnect automatically or do we need to do that ourselves?

**Comment by KmanOz** [comment]
OK will check but first some background. Stopped responding again, In fact last night the whole thing just stopped. I killed the service and started it again but the accessory became undiscoverable in Apple Home. I decided to remove the accessory from Apple Home and search and add it again but just wouldn't find it even though service was running normally. I then removed the whole home from Apple Home and setup from scratch and still nothing. I then emptied the /persist & /accessories dirs and restarted the server and it came back and is working but 2 way comms is back to 1 way comms after a period which I didn't take note of.

I will follow what you said but when it last happened, I actually rebooted my iPhone (cause it's iOS10 beta although very stable) and it didn't fix the issue so point number 2 is NO. I had to kill the service and restart it for 2 way comms to resume. It's back to 1-way comms again after complete fresh install so I will enable logs and lets see.

**Comment by maddox** [comment]
I still don't understand the "one way" issue. homebridge has never been designed to expect to cache state, which in the HA world is sort of a bad idea. That's why there's setters AND getters. 

Is this just an issue that has popped up with how iOS 10's native Home stuff works? Because with the third party Home app, you can see homebridge make the calls to fetch state when Home needs show the current state. 

So does iOS 10's stuff not trigger this? Is this just a bug in homebridge?

Relying on SSE smells like HomeKit is expecting the specific state to already exist when it queries the "hub". Why even have a getter?

What am I missing here?

**Comment by shmuelzon** [comment]
AFAIK, HomeKit uses getters to get the current values. Once it has them (and needs to) it will make a separate request to the HAP server requesting push updates. I think you can see these requests in the log... This is essentially the same model as HA, you have getters and setters along with a method to get updates.
The phone will only request updates if it's currently displaying the devices and probably if there is some rule/trigger based on a device characteristic.
I've seen the same behaviour in both iOS 9 and 10.

**Comment by KmanOz** [comment]
Right now (when it works) I can have Apple Home open on the iPhone and then turn on a light using HA on a browser and it's state will be reflected back in Apple Home. When SSE breaks, the state is not reflected in Apple Home. Apple Home still has the ability to control the light in HA though and it does sync up again to show the proper state. Does that make sense? That's what I mean by one way communication.

I just checked. It wasn't working just now. I killed the service, restarted and is working correctly. 

What else do you need me to check?

**Comment by shmuelzon** [comment]
I would be happy to see the debug logs when the issue happens. If you could also annotate the logs before and after you turn something on/off via the Home app and also before and after you turn something on/off via HA it would be greatly appreciated.

**Comment by shmuelzon** [comment]
BTW - is this with a specific component type (e.g. only lights) or with all devices?

**Comment by KmanOz** [comment]
OK I will do this over the weekend. Only tried 1 light ATM.

**Comment by KmanOz** [comment]
Sorry guys got busy and forgot about this. Will do it this week but I can say this, when it is working correctly and I open a rollershutter from HA or through an automation in HA., Apple Home will display a popup on screen to indicate that the door is open (or up or whatever terminology works for you). When SSE breaks no notifications. So further to your question above, it happens on more than just lights. More this coming week.
